name: ws_build

on:
  push:
    branches:
      - main

jobs:
  workspace-build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: workspace

      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.0
        with:
          distro: humble

      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.0
      
      - name: Test workspace
        run: |
          source install/setup.bash
          colcon test --return-code-on-test-failure
